export const projectsData = [
  {
    id: "urban-oasis-residence",
    title: "Urban Oasis Residence",
    category: "Residential",
    location: "New York, NY",
    year: "2022",
    size: "4,500 sq ft",
    client: "Private Client",
    coverImage: "/placeholder.svg?height=800&width=1200",
    gallery: [
      "/placeholder.svg?height=800&width=800",
      "/placeholder.svg?height=800&width=800",
      "/placeholder.svg?height=800&width=800",
      "/placeholder.svg?height=800&width=800",
      "/placeholder.svg?height=800&width=800",
      "/placeholder.svg?height=800&width=800",
    ],
    services: ["Architectural Design", "Interior Design", "Landscape Design", "Construction Administration"],
    description: [
      "Urban Oasis Residence is a modern family home designed to create a tranquil retreat within the bustling city. The design emphasizes the connection between indoor and outdoor spaces, with large windows and sliding glass doors that open to a private courtyard garden.",
      "The home features a minimalist aesthetic with warm materials, including natural stone, wood, and concrete. The open floor plan maximizes natural light and creates a seamless flow between living spaces, while carefully designed private areas provide quiet retreats for family members.",
      "Sustainability was a key consideration in the design, with features including a green roof, solar panels, rainwater harvesting system, and high-performance insulation. The result is a home that not only provides a comfortable living environment but also minimizes its environmental footprint.",
    ],
  },
  {
    id: "horizon-tower",
    title: "Horizon Tower",
    category: "Commercial",
    location: "Chicago, IL",
    year: "2021",
    size: "125,000 sq ft",
    client: "Horizon Developments",
    coverImage: "/placeholder.svg?height=800&width=1200",
    gallery: [
      "/placeholder.svg?height=800&width=800",
      "/placeholder.svg?height=800&width=800",
      "/placeholder.svg?height=800&width=800",
      "/placeholder.svg?height=800&width=800",
      "/placeholder.svg?height=800&width=800",
      "/placeholder.svg?height=800&width=800",
    ],
    services: ["Architectural Design", "Structural Engineering", "Sustainable Design", "Project Management"],
    description: [
      "Horizon Tower is a striking addition to the Chicago skyline, designed to maximize views while minimizing environmental impact. The 30-story mixed-use building includes office spaces, retail, and a rooftop garden accessible to all tenants.",
      "The façade features a dynamic glass curtain wall system that responds to environmental conditions, reducing solar heat gain while maintaining abundant natural light. The building's distinctive form tapers as it rises, creating a slender profile that optimizes floor plates and reduces wind loads.",
      "Sustainability is integrated throughout the design, with features including a high-performance building envelope, energy-efficient mechanical systems, and rainwater collection. The project achieved LEED Platinum certification, setting a new standard for sustainable commercial architecture in the city.",
    ],
  },
  {
    id: "cultural-arts-center",
    title: "Cultural Arts Center",
    category: "Cultural",
    location: "San Francisco, CA",
    year: "2023",
    size: "75,000 sq ft",
    client: "City of San Francisco",
    coverImage: "/placeholder.svg?height=800&width=1200",
    gallery: [
      "/placeholder.svg?height=800&width=800",
      "/placeholder.svg?height=800&width=800",
      "/placeholder.svg?height=800&width=800",
      "/placeholder.svg?height=800&width=800",
      "/placeholder.svg?height=800&width=800",
      "/placeholder.svg?height=800&width=800",
    ],
    services: [
      "Architectural Design",
      "Interior Design",
      "Acoustic Engineering",
      "Lighting Design",
      "Construction Administration",
    ],
    description: [
      "The Cultural Arts Center is a vibrant community hub designed to celebrate and nurture the arts. The building houses a 500-seat performance theater, art galleries, studios, classrooms, and public gathering spaces that foster creativity and collaboration.",
      "The design draws inspiration from the city's topography and cultural diversity, with a series of terraced volumes that create a dynamic form. The façade combines transparent glass with perforated metal panels that filter light and create ever-changing patterns throughout the day.",
      "Inside, flexible spaces can be reconfigured to accommodate various events and exhibitions. Natural light floods the public areas through strategically placed skylights and clerestory windows. The project exemplifies our commitment to creating cultural spaces that are both functional and inspiring.",
    ],
  },
]

