export const projectsData = [
  
  
  {
    id: "bungalow-at-chambli",
    title: "Bungalow at Chambli",
    category: "Residential",
    location: "Chambli",
    year: "2023",
    size: "75,000 sq ft",
    client: "City of Chambli",
    coverImage: "/images/chambli1.jpg",
    gallery: [
      "/images/chambli1.jpg",
      "/images/chambli2.jpg",
      "/images/chambli3.jpg",
    ],
    services: [
      "Architectural Design",
      "Interior Design",
      "Acoustic Engineering",
      "Lighting Design",
      "Construction Administration",
    ],
    description: [
      "The Cultural Arts Center is a vibrant community hub designed to celebrate and nurture the arts. The building houses a 500-seat performance theater, art galleries, studios, classrooms, and public gathering spaces that foster creativity and collaboration.",
      "The design draws inspiration from the city's topography and cultural diversity, with a series of terraced volumes that create a dynamic form. The façade combines transparent glass with perforated metal panels that filter light and create ever-changing patterns throughout the day.",
      "Inside, flexible spaces can be reconfigured to accommodate various events and exhibitions. Natural light floods the public areas through strategically placed skylights and clerestory windows. The project exemplifies our commitment to creating cultural spaces that are both functional and inspiring.",
    ],
  },
 
  {
    id: "chiniwala-farms",
    title: "Chiniwala Farms (Nandanvan Farms)",
    category: "Sustainable",
    location: "Bhosalewadi, Maharashtra",
    year: "2023",
    size: "75,000 sq ft",
    client: "City of Maharashtra",
    coverImage: "/images/chiniwala1.jpg",
    gallery: [
      "/images/chiniwala1.jpg",
      "/images/chiniwala2.jpg",
      "/images/chiniwala3.jpg",
    ],
    services: [
      "Architectural Design",
      "Interior Design",
      "Acoustic Engineering",
      "Lighting Design",
      "Construction Administration",
    ],
    description: [
      "The Cultural Arts Center is a vibrant community hub designed to celebrate and nurture the arts. The building houses a 500-seat performance theater, art galleries, studios, classrooms, and public gathering spaces that foster creativity and collaboration.",
      "The design draws inspiration from the city's topography and cultural diversity, with a series of terraced volumes that create a dynamic form. The façade combines transparent glass with perforated metal panels that filter light and create ever-changing patterns throughout the day.",
      "Inside, flexible spaces can be reconfigured to accommodate various events and exhibitions. Natural light floods the public areas through strategically placed skylights and clerestory windows. The project exemplifies our commitment to creating cultural spaces that are both functional and inspiring.",
    ],
  },
  {
    id: "bungalow-at-wadachi-wadi",
    title: "Bungalow at Wadachi Wadi",
    category: "Residential",
    location: "Wadachi Wadi",
    year: "2023",
    size: "75,000 sq ft",
    client: "City of Wadachi Wadi",
    coverImage: "/images/wadachi1.jpg",
    gallery: [
      "/images/wadachi1.jpg",
      "/images/wadachi2.jpg",
      "/images/wadachi3.jpg",
    ],
    services: [
      "Architectural Design",
      "Interior Design",
      "Acoustic Engineering",
      "Lighting Design",
      "Construction Administration",
    ],
    description: [
      "The Cultural Arts Center is a vibrant community hub designed to celebrate and nurture the arts. The building houses a 500-seat performance theater, art galleries, studios, classrooms, and public gathering spaces that foster creativity and collaboration.",
      "The design draws inspiration from the city's topography and cultural diversity, with a series of terraced volumes that create a dynamic form. The façade combines transparent glass with perforated metal panels that filter light and create ever-changing patterns throughout the day.",
      "Inside, flexible spaces can be reconfigured to accommodate various events and exhibitions. Natural light floods the public areas through strategically placed skylights and clerestory windows. The project exemplifies our commitment to creating cultural spaces that are both functional and inspiring.",
    ],
  },
  {
    id: "temple-at-baramati",
    title: "Temple at Baramati",
    category: "Cultural",
    location: "Baramati, Maharashtra",
    year: "2023",
    size: "75,000 sq ft",
    client: "City of Maharashtra",
    coverImage: "/images/temple.jpg",
    gallery: [
      "/images/temple.jpg",
      "/images/temple.jpg",
      
    ],
    services: [
      "Architectural Design",
      "Interior Design",
      "Acoustic Engineering",
      "Lighting Design",
      "Construction Administration",
    ],
    description: [
      "The Cultural Arts Center is a vibrant community hub designed to celebrate and nurture the arts. The building houses a 500-seat performance theater, art galleries, studios, classrooms, and public gathering spaces that foster creativity and collaboration.",
      "The design draws inspiration from the city's topography and cultural diversity, with a series of terraced volumes that create a dynamic form. The façade combines transparent glass with perforated metal panels that filter light and create ever-changing patterns throughout the day.",
      "Inside, flexible spaces can be reconfigured to accommodate various events and exhibitions. Natural light floods the public areas through strategically placed skylights and clerestory windows. The project exemplifies our commitment to creating cultural spaces that are both functional and inspiring.",
    ],
  },
  {
    id: "corporate-office-us-food-ltd-at-delhi",
    title: "Corporate Office US Food Ltd at Delhi",
    category: "Commercial",
    location: "Delhi",
    year: "2023",
    size: "75,000 sq ft",
    client: "City of Delhi",
    coverImage: "/images/office1.jpg",
    gallery: [
      "/images/office1.jpg",
      "/images/office2.jpg",
      "/images/office3.jpg",
      
    ],
    services: [
      "Architectural Design",
      "Interior Design",
      "Acoustic Engineering",
      "Lighting Design",
      "Construction Administration",
    ],
    description: [
      "The Cultural Arts Center is a vibrant community hub designed to celebrate and nurture the arts. The building houses a 500-seat performance theater, art galleries, studios, classrooms, and public gathering spaces that foster creativity and collaboration.",
      "The design draws inspiration from the city's topography and cultural diversity, with a series of terraced volumes that create a dynamic form. The façade combines transparent glass with perforated metal panels that filter light and create ever-changing patterns throughout the day.",
      "Inside, flexible spaces can be reconfigured to accommodate various events and exhibitions. Natural light floods the public areas through strategically placed skylights and clerestory windows. The project exemplifies our commitment to creating cultural spaces that are both functional and inspiring.",
    ],
  },
  {
    id: "dr-p-a-inamdar-university-office",
    title: "Dr P A Inamdar University Office",
    category: "Commercial",
    location: "Pune",
    year: "2023",
    size: "75,000 sq ft",
    client: "City of Pune",
    coverImage: "/images/dr-p-a-inamdar1.avif",
    gallery: [
      "/images/dr-p-a-inamdar1.avif",
      "/images/dr-p-a-inamdar2.jpg",
      "/images/dr-p-a-inamdar3.jpg",
      
    ],
    services: [
      "Architectural Design",
      "Interior Design",
      "Acoustic Engineering",
      "Lighting Design",
      "Construction Administration",
    ],
    description: [
      "The Cultural Arts Center is a vibrant community hub designed to celebrate and nurture the arts. The building houses a 500-seat performance theater, art galleries, studios, classrooms, and public gathering spaces that foster creativity and collaboration.",
      "The design draws inspiration from the city's topography and cultural diversity, with a series of terraced volumes that create a dynamic form. The façade combines transparent glass with perforated metal panels that filter light and create ever-changing patterns throughout the day.",
      "Inside, flexible spaces can be reconfigured to accommodate various events and exhibitions. Natural light floods the public areas through strategically placed skylights and clerestory windows. The project exemplifies our commitment to creating cultural spaces that are both functional and inspiring.",
    ],
  },
  {
    id: "guest-villa-at-saudi-arabia",
    title: "Guest Villa at Saudi Arabia",
    category: "Residential",
    location: "Saudi Arabia",
    year: "2023",
    size: "75,000 sq ft",
    client: "City of Saudi Arabia",
    coverImage: "/images/guestvilla1.jpg",
    gallery: [
      "/images/guestvilla1.jpg",
      "/images/guestvilla2.jpg",
      "/images/guestvilla3.jpg",
      
      
    ],
    services: [
      "Architectural Design",
      "Interior Design",
      "Acoustic Engineering",
      "Lighting Design",
      "Construction Administration",
    ],
    description: [
      "The Cultural Arts Center is a vibrant community hub designed to celebrate and nurture the arts. The building houses a 500-seat performance theater, art galleries, studios, classrooms, and public gathering spaces that foster creativity and collaboration.",
      "The design draws inspiration from the city's topography and cultural diversity, with a series of terraced volumes that create a dynamic form. The façade combines transparent glass with perforated metal panels that filter light and create ever-changing patterns throughout the day.",
      "Inside, flexible spaces can be reconfigured to accommodate various events and exhibitions. Natural light floods the public areas through strategically placed skylights and clerestory windows. The project exemplifies our commitment to creating cultural spaces that are both functional and inspiring.",
    ],
  },
  {
    id: "bungalow-at-magarpatta",
    title: "Bungalow at Magarpatta",
    category: "Residential",
    location: "Magarpatta",
    year: "2023",
    size: "75,000 sq ft",
    client: "City of Magarpatta",
    coverImage: "/images/magarpatta1.jpg",
    gallery: [
      "/images/magarpatta1.jpg",
      "/images/office2.jpg",

      
    ],
    services: [
      "Architectural Design",
      "Interior Design",
      "Acoustic Engineering",
      "Lighting Design",
      "Construction Administration",
    ],
    description: [
      "The Cultural Arts Center is a vibrant community hub designed to celebrate and nurture the arts. The building houses a 500-seat performance theater, art galleries, studios, classrooms, and public gathering spaces that foster creativity and collaboration.",
      "The design draws inspiration from the city's topography and cultural diversity, with a series of terraced volumes that create a dynamic form. The façade combines transparent glass with perforated metal panels that filter light and create ever-changing patterns throughout the day.",
      "Inside, flexible spaces can be reconfigured to accommodate various events and exhibitions. Natural light floods the public areas through strategically placed skylights and clerestory windows. The project exemplifies our commitment to creating cultural spaces that are both functional and inspiring.",
    ],
  },
  {
    id: "biscuit-factory-at-gajroula-up",
    title: "Biscuit Factory at Gajroula UP",
    category: "Commercial",
    location: "Gajroula UP",
    year: "2023",
    size: "75,000 sq ft",
    client: "City of Gajroula UP",
    coverImage: "/images/gajroula1.jpg",
    gallery: [
      "/images/gajroula1.jpg",
      "/images/gajroula2.jpg",
      "/images/office1.jpg",
      
      
    ],
    services: [
      "Architectural Design",
      "Interior Design",
      "Acoustic Engineering",
      "Lighting Design",
      "Construction Administration",
    ],
    description: [
      "The Cultural Arts Center is a vibrant community hub designed to celebrate and nurture the arts. The building houses a 500-seat performance theater, art galleries, studios, classrooms, and public gathering spaces that foster creativity and collaboration.",
      "The design draws inspiration from the city's topography and cultural diversity, with a series of terraced volumes that create a dynamic form. The façade combines transparent glass with perforated metal panels that filter light and create ever-changing patterns throughout the day.",
      "Inside, flexible spaces can be reconfigured to accommodate various events and exhibitions. Natural light floods the public areas through strategically placed skylights and clerestory windows. The project exemplifies our commitment to creating cultural spaces that are both functional and inspiring.",
    ],
  },
  {
    id: "agha-khan-jamat-khana-at-mumbai",
    title: "Agha Khan Jamat Khana at Mumbai",
    category: "Commercial",
    location: "Mumbai",
    year: "2021",
    size: "125,000 sq ft",
    client: "Horizon Developments",
    coverImage: "/placeholder.svg?height=800&width=1200",
    gallery: [
      "/placeholder.svg?height=800&width=800",
      "/placeholder.svg?height=800&width=800",
      "/placeholder.svg?height=800&width=800",
      "/placeholder.svg?height=800&width=800",
      "/placeholder.svg?height=800&width=800",
      "/placeholder.svg?height=800&width=800",
    ],
    services: ["Architectural Design", "Structural Engineering", "Sustainable Design", "Project Management"],
    description: [
      "Horizon Tower is a striking addition to the Chicago skyline, designed to maximize views while minimizing environmental impact. The 30-story mixed-use building includes office spaces, retail, and a rooftop garden accessible to all tenants.",
      "The façade features a dynamic glass curtain wall system that responds to environmental conditions, reducing solar heat gain while maintaining abundant natural light. The building's distinctive form tapers as it rises, creating a slender profile that optimizes floor plates and reduces wind loads.",
      "Sustainability is integrated throughout the design, with features including a high-performance building envelope, energy-efficient mechanical systems, and rainwater collection. The project achieved LEED Platinum certification, setting a new standard for sustainable commercial architecture in the city.",
    ],
  },
  {
    id: "pipe-factory-at-saudi-arabia",
    title: "Pipe factory at Saudi Arabia",
    category: "Industrial",
    location: "Saudi Arabia",
    year: "2023",
    size: "75,000 sq ft",
    client: "City of Saudi Arabia",
    coverImage: "/placeholder.svg?height=800&width=1200",
    gallery: [
      "/placeholder.svg?height=800&width=800",
      "/placeholder.svg?height=800&width=800",
      "/placeholder.svg?height=800&width=800",
    ],
    services: [
      "Architectural Design",
      "Interior Design",
      "Acoustic Engineering",
      "Lighting Design",
      "Construction Administration",
    ],
    description: [
      "The Cultural Arts Center is a vibrant community hub designed to celebrate and nurture the arts. The building houses a 500-seat performance theater, art galleries, studios, classrooms, and public gathering spaces that foster creativity and collaboration.",
      "The design draws inspiration from the city's topography and cultural diversity, with a series of terraced volumes that create a dynamic form. The façade combines transparent glass with perforated metal panels that filter light and create ever-changing patterns throughout the day.",
      "Inside, flexible spaces can be reconfigured to accommodate various events and exhibitions. Natural light floods the public areas through strategically placed skylights and clerestory windows. The project exemplifies our commitment to creating cultural spaces that are both functional and inspiring.",
    ],
  },
]

